// Azkar data for Muslim Life OS
export const MORNING_AZKAR = [
  {
    id: 'm1',
    arabic: 'أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ',
    transliteration: 'Asbahna wa asbahal mulku lillahi, walhamdu lillahi, la ilaha illallahu wahdahu la sharika lah',
    translation: 'We have reached the morning and at this very time the sovereignty belongs to Allah. All praise is for Allah. None has the right to be worshipped except Allah, alone, without partner.',
    count: 1,
    category: 'morning',
  },
  {
    id: 'm2',
    arabic: 'اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ وَإِلَيْكَ النُّشُورُ',
    transliteration: 'Allahumma bika asbahna, wa bika amsayna, wa bika nahya, wa bika namutu wa ilaykan-nushur',
    translation: 'O Allah, by Your leave we have reached the morning and by Your leave we have reached the evening, by Your leave we live and die and unto You is our return.',
    count: 1,
    category: 'morning',
  },
  {
    id: 'm3',
    arabic: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ',
    transliteration: 'Subhan Allahi wa bihamdihi',
    translation: 'Glory is to Allah and praise is to Him.',
    count: 100,
    category: 'morning',
  },
  {
    id: 'm4',
    arabic: 'لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
    transliteration: "La ilaha illallahu wahdahu la sharika lah, lahul mulku wa lahul hamdu wa huwa 'ala kulli shay'in qadir",
    translation: 'None has the right to be worshipped except Allah, alone, without partner, to Him belongs all sovereignty and praise, and He is over all things omnipotent.',
    count: 10,
    category: 'morning',
  },
  {
    id: 'm5',
    arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ',
    transliteration: 'Allahumma anta rabbi la ilaha illa ant, khalaqtani wa ana abduk',
    translation: 'O Allah, You are my Lord, none has the right to be worshipped except You, You created me and I am Your servant.',
    count: 1,
    category: 'morning',
  },
];

export const EVENING_AZKAR = [
  {
    id: 'e1',
    arabic: 'أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ',
    transliteration: 'Amsayna wa amsal mulku lillahi, walhamdu lillahi, la ilaha illallahu wahdahu la sharika lah',
    translation: 'We have reached the evening and at this very time the sovereignty belongs to Allah. All praise is for Allah.',
    count: 1,
    category: 'evening',
  },
  {
    id: 'e2',
    arabic: 'اللَّهُمَّ بِكَ أَمْسَيْنَا، وَبِكَ أَصْبَحْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ وَإِلَيْكَ الْمَصِيرُ',
    transliteration: 'Allahumma bika amsayna, wa bika asbahna, wa bika nahya, wa bika namutu wa ilaykal masir',
    translation: 'O Allah, by Your leave we have reached the evening and by Your leave we have reached the morning, by Your leave we live and die and unto You is our return.',
    count: 1,
    category: 'evening',
  },
  {
    id: 'e3',
    arabic: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ',
    transliteration: "A'udhu bikalimatillahi at-tammati min sharri ma khalaq",
    translation: 'I take refuge in the perfect words of Allah from the evil of what He has created.',
    count: 3,
    category: 'evening',
  },
  {
    id: 'e4',
    arabic: 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ',
    transliteration: 'Bismillahil ladhi la yadurru ma asmihi shay un fil ardi wa la fis sama',
    translation: 'In the name of Allah with whose name nothing is harmed on earth nor in the heavens and He is the All-Seeing, All-Knowing.',
    count: 3,
    category: 'evening',
  },
  {
    id: 'e5',
    arabic: 'اللَّهُمَّ صَلِّ وَسَلِّمْ عَلَى نَبِيِّنَا مُحَمَّدٍ',
    transliteration: 'Allahumma salli wa sallim ala nabiyyina Muhammad',
    translation: 'O Allah, send prayers and peace upon our Prophet Muhammad.',
    count: 10,
    category: 'evening',
  },
];

export const AFTER_SALAH_AZKAR = [
  {
    id: 'a1',
    arabic: 'أَسْتَغْفِرُ اللَّهَ',
    transliteration: 'Astaghfirullah',
    translation: 'I seek forgiveness from Allah.',
    count: 3,
    category: 'afterSalah',
  },
  {
    id: 'a2',
    arabic: 'اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ، تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالْإِكْرَامِ',
    transliteration: 'Allahumma antas salam wa minkas salam, tabarakta ya dhal jalali wal ikram',
    translation: 'O Allah, You are As-Salaam (the One free from all defects and deficiencies) and from You is all peace, blessed are You O possessor of majesty and honour.',
    count: 1,
    category: 'afterSalah',
  },
  {
    id: 'a3',
    arabic: 'سُبْحَانَ اللَّهِ',
    transliteration: 'Subhan Allah',
    translation: 'Glory is to Allah.',
    count: 33,
    category: 'afterSalah',
  },
  {
    id: 'a4',
    arabic: 'الْحَمْدُ لِلَّهِ',
    transliteration: 'Alhamdulillah',
    translation: 'All praise is for Allah.',
    count: 33,
    category: 'afterSalah',
  },
  {
    id: 'a5',
    arabic: 'اللَّهُ أَكْبَرُ',
    transliteration: 'Allahu Akbar',
    translation: 'Allah is the Greatest.',
    count: 34,
    category: 'afterSalah',
  },
];

export const DUA_COLLECTIONS = [
  {
    id: 'd1',
    category: 'Morning',
    arabic: 'اللَّهُمَّ بِكَ أَصْبَحْنَا وَبِكَ أَمْسَيْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوتُ وَإِلَيْكَ النُّشُورُ',
    translation: 'O Allah, by Your leave we have reached the morning and by Your leave we have reached the evening...',
    source: 'Tirmidhi',
  },
  {
    id: 'd2',
    category: 'Sleep',
    arabic: 'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا',
    translation: 'In Your name O Allah, I die and I live.',
    source: 'Bukhari',
  },
  {
    id: 'd3',
    category: 'Meals',
    arabic: 'بِسْمِ اللَّهِ وَعَلَى بَرَكَةِ اللَّهِ',
    translation: 'In the name of Allah and with the blessings of Allah.',
    source: 'Abu Dawud',
  },
  {
    id: 'd4',
    category: 'Anxiety',
    arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ',
    translation: 'O Allah, I seek refuge in You from worry and grief.',
    source: 'Bukhari',
  },
  {
    id: 'd5',
    category: 'Travel',
    arabic: 'سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ',
    translation: 'Glorified is the One Who has subjected this to us, and we were not capable of that.',
    source: 'Abu Dawud',
  },
  {
    id: 'd6',
    category: 'Forgiveness',
    arabic: 'رَبَّنَا ظَلَمْنَا أَنفُسَنَا وَإِن لَّمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُونَنَّ مِنَ الْخَاسِرِينَ',
    translation: 'Our Lord, we have wronged ourselves, and if You do not forgive us and have mercy upon us, we will surely be among the losers.',
    source: 'Quran 7:23',
  },
  {
    id: 'd7',
    category: 'Health',
    arabic: 'اللَّهُمَّ عَافِنِي فِي بَدَنِي، اللَّهُمَّ عَافِنِي فِي سَمْعِي، اللَّهُمَّ عَافِنِي فِي بَصَرِي',
    translation: 'O Allah, grant me health in my body. O Allah, grant me health in my hearing. O Allah, grant me health in my sight.',
    source: 'Abu Dawud',
  },
  {
    id: 'd8',
    category: 'Protection',
    arabic: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ',
    translation: 'I take refuge in the perfect words of Allah from the evil of what He has created.',
    source: 'Muslim',
  },
];

export const HADITHS = [
  {
    id: 'h1',
    arabic: 'إِنَّمَا الْأَعْمَالُ بِالنِّيَّاتِ',
    translation: 'Actions are but by intentions, and every man shall have only that which he intended.',
    narrator: 'Umar ibn al-Khattab (RA)',
    source: 'Bukhari & Muslim',
    category: 'Intentions',
  },
  {
    id: 'h2',
    arabic: 'الدِّينُ النَّصِيحَةُ',
    translation: 'Religion is sincerity (giving sincere advice).',
    narrator: 'Tamim al-Dari (RA)',
    source: 'Muslim',
    category: 'Character',
  },
  {
    id: 'h3',
    arabic: 'خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ',
    translation: 'The best among you are those who learn the Quran and teach it.',
    narrator: 'Uthman ibn Affan (RA)',
    source: 'Bukhari',
    category: 'Quran',
  },
  {
    id: 'h4',
    arabic: 'مَنْ صَامَ رَمَضَانَ إِيمَانًا وَاحْتِسَابًا غُفِرَ لَهُ مَا تَقَدَّمَ مِنْ ذَنْبِهِ',
    translation: 'Whoever fasts Ramadan out of faith and hope for reward, his previous sins will be forgiven.',
    narrator: 'Abu Hurairah (RA)',
    source: 'Bukhari & Muslim',
    category: 'Fasting',
  },
  {
    id: 'h5',
    arabic: 'مَا مِنْ مُسْلِمٍ يَغْرِسُ غَرْسًا فَيَأْكُلُ مِنْهُ إِنْسَانٌ أَوْ دَابَّةٌ إِلَّا كَانَ لَهُ صَدَقَةٌ',
    translation: 'There is no Muslim who plants a tree, and then a human or animal eats from it, except that it will be counted as charity for him.',
    narrator: 'Anas ibn Malik (RA)',
    source: 'Bukhari & Muslim',
    category: 'Charity',
  },
];
